<template>
    <div>
        <header>
            <span class="left">商品分类</span>
            <div class="right">
                手机至高享24期免息
                <span></span>
            </div>
        </header>
        <section>
            <nav>
                <ul class="type">
                    <li v-for="(item,index) in types" @click="change(item,index)" :class="{current:num==index}">
                        {{item.con}}
                    </li>
                </ul>
            </nav>
            <main>
                <component :is="msg" :items="product"></component>
            </main>
        </section>
    </div>
</template>
<script>
    import recommend from './recommend.vue';
    import smart from './smart.vue';
    import family from './family.vue';
    export default{
        data(){
            return{
                msg:"v-recommend",
                product:"",
                num:0,
                types:[
                    {
                        con:"热门推荐",
                        id:"v-recommend"
                    },
                    {
                        con:"手机数码",
                        id:"v-smart"
                    },
                    {
                        con:"大家电",
                        id:"v-family"
                    },
                    {
                        con:"电脑办公",
                        id:"v-smart"
                    },
                    {
                        con:"厨卫大电",
                        id:"v-family"
                    },
                    {
                        con:"生活家电",
                        id:"v-family"
                    },
                    {
                        con:"食品酒水",
                        id:"v-smart"
                    },
                    {
                        con:"个人护理",
                        id:"v-smart"
                    },
                    {
                        con:"美妆护肤",
                        id:"v-smart"
                    },
                    {
                        con:"奶粉尿裤",
                        id:"v-smart"
                    },
                    {
                        con:"苏宁国际",
                        id:"v-smart"
                    },
                    {
                        con:"珠宝首饰",
                        id:"v-smart"
                    },
                    {
                        con:"品质男装",
                        id:"v-smart"
                    }
                ]
            }
        },
        methods:{
            change(a,b){
                console.log(1);
                this.num = b;
                this.msg = a.id;
                if(a.con=="手机数码"){
                    this.product = {
                        title:"手机",
                        products:[
                            {
                                title:"热销大牌",
                                list:[
                                    {
                                        src:"./src/assets/images/p1.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i1.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i2.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i3.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i4.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i5.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i6.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i7.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i8.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i9.png",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i10.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i11.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i12.png",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i13.jpg",
                                        con:""
                                    },
                                    {
                                        src:"./src/assets/images/i14.jpg",
                                        con:""
                                    }
                                ]
                            },
                            {
                            
                                title:"手机通讯",
                                list:[
                                    {
                                        src:"./src/assets/images/i15.jpg",
                                        con:"全部手机"
                                    },
                                    {
                                        src:"./src/assets/images/i16.jpg",
                                        con:"全部手机"
                                    },
                                    {
                                        src:"./src/assets/images/i17.jpg",
                                        con:"全部手机"
                                    },
                                    {
                                        src:"./src/assets/images/i18.jpg",
                                        con:"全部手机"
                                    },
                                    {
                                        src:"./src/assets/images/i19.jpg",
                                        con:"全部手机"
                                    },
                                    {
                                        src:"./src/assets/images/i20.jpg",
                                        con:"全部手机"
                                    },
                                    {
                                        src:"./src/assets/images/i21.jpg",
                                        con:"全部手机"
                                    },
                                    {
                                        src:"./src/assets/images/i22.jpg",
                                        con:"全部手机"
                                    }
                                ]
                            }
                        ]
                    }
                } else if(a.con=="大家电"){
                    this.product={
                        title:"家电",
                        src:"",
                        products:[
                            {
                                title:"空调",
                                list:[
                                    {
                                        src:"./src/assets/images/c3.jpg",
                                        con:"空调挂机"
                                    },
                                    {
                                        src:"./src/assets/images/k2.png",
                                        con:"空调柜机"
                                    },
                                    {
                                        src:"./src/assets/images/k3.jpg",
                                        con:"移动空调"
                                    },
                                    {
                                        src:"./src/assets/images/k4.jpg",
                                        con:"风管机"
                                    },
                                    {
                                        src:"./src/assets/images/k5.jpg",
                                        con:"多联机"
                                    },
                                    {
                                        src:"./src/assets/images/k9.jpg",
                                        con:"一级能效"
                                    },
                                    {
                                        src:"./src/assets/images/k6.png",
                                        con:"以旧换新"
                                    },
                                    {
                                        src:"./src/assets/images/k7.png",
                                        con:"0元安装"
                                    },
                                    {
                                        src:"./src/assets/images/k8.jpg",
                                        con:"空调免息"
                                    }
                                ]
                            },
                            {
                                title:"冰箱",
                                list:[
                                    {
                                        src:"./src/assets/images/k9.jpg",
                                        con:"空调挂机"
                                    },
                                    {
                                        src:"./src/assets/images/k9.jpg",
                                        con:"空调挂机"
                                    },
                                    {
                                        src:"./src/assets/images/k9.jpg",
                                        con:"空调挂机"
                                    },
                                    {
                                        src:"./src/assets/images/k9.jpg",
                                        con:"空调挂机"
                                    },
                                    {
                                        src:"./src/assets/images/k9.jpg",
                                        con:"空调挂机"
                                    },
                                    {
                                        src:"./src/assets/images/k9.jpg",
                                        con:"空调挂机"
                                    },
                                    {
                                        src:"./src/assets/images/k9.jpg",
                                        con:"空调挂机"
                                    }
                                ]
                            },
                            {
                                title:"洗衣机",
                                list:[
                                    {
                                        src:"./src/assets/images/k10.jpg",
                                        con:"洗烘一体机"
                                    },
                                    {
                                        src:"./src/assets/images/k10.jpg",
                                        con:"洗烘一体机"
                                    },
                                    {
                                        src:"./src/assets/images/k10.jpg",
                                        con:"洗烘一体机"
                                    },
                                    {
                                        src:"./src/assets/images/k10.jpg",
                                        con:"洗烘一体机"
                                    },
                                    {
                                        src:"./src/assets/images/k10.jpg",
                                        con:"洗烘一体机"
                                    }
                                ]
                            },
                            {
                                title:"电视",
                                list:[
                                    {
                                        src:"./src/assets/images/k11.jpg",
                                        con:"电视"
                                    },
                                    {
                                        src:"./src/assets/images/k11.jpg",
                                        con:"电视"
                                    },
                                    {
                                        src:"./src/assets/images/k11.jpg",
                                        con:"电视"
                                    },
                                    {
                                        src:"./src/assets/images/k11.jpg",
                                        con:"电视"
                                    },
                                    {
                                        src:"./src/assets/images/k11.jpg",
                                        con:"电视"
                                    },
                                    {
                                        src:"./src/assets/images/k11.jpg",
                                        con:"电视"
                                    },
                                    {
                                        src:"./src/assets/images/k11.jpg",
                                        con:"电视"
                                    }
                                    
                                    
                                ]
                            },
                            {
                                title:"集成家电",
                                list:[
                                    {
                                        src:"./src/assets/images/k12.jpg",
                                        con:"悬挂式新风"
                                    },
                                    {
                                        src:"./src/assets/images/k12.jpg",
                                        con:"悬挂式新风"
                                    },
                                    {
                                        src:"./src/assets/images/k12.jpg",
                                        con:"悬挂式新风"
                                    },
                                    {
                                        src:"./src/assets/images/k12.jpg",
                                        con:"悬挂式新风"
                                    },
                                    {
                                        src:"./src/assets/images/k12.jpg",
                                        con:"悬挂式新风"
                                    },
                                    {
                                        src:"./src/assets/images/k12.jpg",
                                        con:"悬挂式新风"
                                    },
                                    {
                                        src:"./src/assets/images/k12.jpg",
                                        con:"悬挂式新风"
                                    }
                                    
                                ]
                            },
                            {
                                title:"商用电器",
                                list:[
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    },
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    },
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    },
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    },
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    },
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    },
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    },
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    },
                                    {
                                        src:"./src/assets/images/k13.jpg",
                                        con:"商用发酵机"
                                    }
                                ]
                            }
                        ]
                    }
                } else if(a.con == "电脑办公"){
                    this.product = {
                        title:"电脑办公",
                        src:"",
                        products:[
                            {
                                title:"热销品牌",
                                list:[
                                    {
                                        src:"./src/assets/images/d1.jpg",
                                        con:"",
                                    },
                                    {
                                        src:"./src/assets/images/d1.jpg",
                                        con:"",
                                    },
                                    {
                                        src:"./src/assets/images/d1.jpg",
                                        con:"",
                                    },
                                    {
                                        src:"./src/assets/images/d1.jpg",
                                        con:"",
                                    },
                                    {
                                        src:"./src/assets/images/d1.jpg",
                                        con:"",
                                    },
                                    {
                                        src:"./src/assets/images/d1.jpg",
                                        con:"",
                                    },
                                    {
                                        src:"./src/assets/images/d1.jpg",
                                        con:"",
                                    }
                                ]
                            },
                            {
                                title:"电脑整机",
                                list:[
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    },
                                    {
                                        src:"./src/assets/images/d2.jpg",
                                        con:"笔记本"
                                    }
                                ]
                            }
                        ]
                    }

                } else if(a.con == "厨卫大电"){
                    this.product = {
                        title:"厨卫电器",
                        src:"./src/assets/images/c_t1.jpg",
                        products:[
                            {
                                title:"厨房电器",
                                list:[
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    },
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    },
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    },
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    },
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    },
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    },
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    },
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    },
                                    {
                                        src:"./src/assets/images/d3.jpg",
                                        con:"油烟机"
                                    }
                                ]
                            },
                            {
                                title:"卫浴电器",
                                list:[
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    },
                                    {
                                        src:"./src/assets/images/d4.jpg",
                                        con:"燃气热水器"
                                    }
                                ]
                            }
                        ]
                    }
                } else if(a.con=="生活家电"){
                    this.product = {
                        title:"生活家电",
                        src:"./src/assets/images/c_t1.jpg",
                        show:0,
                        products:[
                            {
                                title:"热门推荐",
                                list:[
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    },
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    },
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    },
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    },
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    },
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    },
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    },
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    },
                                    {
                                        src:"./src/assets/images/s1.jpg",
                                        con:"烤箱"
                                    }
                                ]
                            },
                            {
                                title:"个护健康",
                                list:[
                                    {
                                        src:"./src/assets/images/s2.jpg",
                                        con:"电动剃须刀"
                                    },
                                    {
                                        src:"./src/assets/images/s2.jpg",
                                        con:"电动剃须刀"
                                    },
                                    {
                                        src:"./src/assets/images/s2.jpg",
                                        con:"电动剃须刀"
                                    },
                                    {
                                        src:"./src/assets/images/s2.jpg",
                                        con:"电动剃须刀"
                                    },
                                    {
                                        src:"./src/assets/images/s2.jpg",
                                        con:"电动剃须刀"
                                    },
                                    {
                                        src:"./src/assets/images/s2.jpg",
                                        con:"电动剃须刀"
                                    },
                                    {
                                        src:"./src/assets/images/s2.jpg",
                                        con:"电动剃须刀"
                                    },
                                    {
                                        src:"./src/assets/images/s2.jpg",
                                        con:"电动剃须刀"
                                    }
                                ]
                            }
                        ]
                    }
                } else if(a.con=="食品酒水"){
                    this.product = {
                        title:"苏宁超市",
                        src:"",
                        products:[
                            {
                                title:'精选品类',
                                list:[
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    },
                                    {
                                        src:'./src/assets/images/food1.jpg',
                                        con:'米'
                                    }
                                ]
                            },
                            {
                                title:"中外名酒",
                                list:[
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    },
                                    {
                                        src:"./src/assets/images/liquor.jpg",
                                        con:'白酒'
                                    }
                                ]
                            }
                        ]
                    }
                } else if(a.con == "个人护理"){
                    this.product = {
                        title:"个人护理",
                        src:"",
                        products:[
                            {
                                title:"美发护发",
                                list:[
                                    {
                                        src:"./src/assets/images/nurse1.jpg",
                                        con:"洗发水"
                                    },
                                    {
                                        src:"./src/assets/images/nurse2.jpg",
                                        con:"洗护套装"
                                    },
                                    {
                                        src:"./src/assets/images/nurse3.jpg",
                                        con:"染烫造型"
                                    },
                                    {
                                        src:"./src/assets/images/nurse4.jpg",
                                        con:"营养水"
                                    },
                                    {
                                        src:"./src/assets/images/nurse5.jpg",
                                        con:"美发工具"
                                    }
                                    
                                ]
                            },
                            {
                                title:"身体护理",
                                list:[
                                    {
                                        src:"./src/assets/images/nurse6.jpg",
                                        con:"沐浴露"
                                    },
                                    {
                                        src:"./src/assets/images/nurse7.jpg",
                                        con:"护手霜"
                                    },
                                    {
                                        src:"./src/assets/images/nurse8.jpg",
                                        con:"护足霜"
                                    },
                                    {
                                        src:"./src/assets/images/nurse9.jpg",
                                        con:"按摩霜"
                                    },
                                    {
                                        src:"./src/assets/images/nurse10.jpg",
                                        con:"润体霜"
                                    },
                                    {
                                        src:"./src/assets/images/nurse11.jpg",
                                        con:"润体乳"
                                    },
                                    {
                                        src:"./src/assets/images/nurse12.jpg",
                                        con:"脱毛"
                                    },
                                    {
                                        src:"./src/assets/images/nurse13.jpg",
                                        con:"丰胸美乳"
                                    }
                                ]
                            },
                            {
                                title:"口腔护理",
                                list:[
                                    {
                                        src:"./src/assets/images/nurse14.jpg",
                                        con:"牙线"
                                    },
                                    {
                                        src:"./src/assets/images/nurse15.jpg",
                                        con:"口腔套装"
                                    },
                                    {
                                        src:"./src/assets/images/nurse16.jpg",
                                        con:"牙粉"
                                    }
                                ]
                            },
                            {
                                title:"品牌墙",
                                list:[
                                    {
                                        src:"./src/assets/images/nurse17.jpg",
                                        con:"海飞丝"
                                    },
                                    {
                                        src:"./src/assets/images/nurse18.jpg",
                                        con:"清扬"
                                    },
                                    {
                                        src:"./src/assets/images/nurse19.jpg",
                                        con:"阿道夫"
                                    },
                                    {
                                        src:"./src/assets/images/nurse20.jpg",
                                        con:"力士"
                                    },
                                    {
                                        src:"./src/assets/images/nurse21.jpg",
                                        con:"飘柔"
                                    },
                                    {
                                        src:"./src/assets/images/nurse22.jpg",
                                        con:"舒肤佳"
                                    },
                                    {
                                        src:"./src/assets/images/nurse23.jpg",
                                        con:"高露洁"
                                    },
                                    {
                                        src:"./src/assets/images/nurse24.jpg",
                                        con:"黑人"
                                    },
                                    {
                                        src:"./src/assets/images/nurse25.jpg",
                                        con:"舒客"
                                    },
                                    {
                                        src:"./src/assets/images/nurse26.jpg",
                                        con:"七度空间"
                                    },
                                    {
                                        src:"./src/assets/images/nurse27.jpg",
                                        con:"护舒宝"
                                    },
                                    {
                                        src:"./src/assets/images/nurse28.jpg",
                                        con:"高洁丝"
                                    }
                                ]
                            }
                        ]
                    }
                } else if(a.con == "美妆护肤"){
                    this.product = {
                        title:"个人护理",
                        src:"",
                        products:[
                            {
                                title:"当季主推",
                                list:[
                                    {
                                        src:"./src/assets/images/h1.jpg",
                                        con:"补水"
                                    },
                                    {
                                        src:"./src/assets/images/h1.jpg",
                                        con:"补水"
                                    },
                                    {
                                        src:"./src/assets/images/h1.jpg",
                                        con:"补水"
                                    }
                                    
                                ]
                            },
                            {
                                title:"拔草推荐",
                                list:[
                                    {
                                        src:"./src/assets/images/h2.jpg",
                                        con:"口红"
                                    },
                                    {
                                        src:"./src/assets/images/h2.jpg",
                                        con:"口红"
                                    },
                                    {
                                        src:"./src/assets/images/h2.jpg",
                                        con:"口红"
                                    }
                                    
                                ]
                            },
                            {
                                title:"面部护肤",
                                list:[
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    },
                                    {
                                        src:"./src/assets/images/h3.jpg",
                                        con:"护肤套装"
                                    }
                                ]
                            },
                            {
                                title:"男士护肤",
                                list:[
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    },
                                    {
                                        src:"./src/assets/images/h4.jpg",
                                        con:"洁面乳"
                                    }
                                    
                                ]
                            },
                            {
                                title:"香水",
                                list:[
                                    {
                                        src:"./src/assets/images/h5.jpg",
                                        con:"女士香水"
                                    },
                                    {
                                        src:"./src/assets/images/h5.jpg",
                                        con:"女士香水"
                                    },
                                    {
                                        src:"./src/assets/images/h5.jpg",
                                        con:"女士香水"
                                    }
                                ]
                            }
                        ]
                    }

                } else if(a.con == "苏宁国际"){
                    this.product = {
                        title:"苏宁国际",
                        src:"",
                        products:[
                            {
                                title:"热门分类",
                                list:[
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    },
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    },
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    },
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    },
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    },
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    },
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    },
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    },
                                    {
                                        src:"./src/assets/images/international1.jpg",
                                        con:"纸尿裤"
                                    }
                                    
                                ]
                            },
                            {
                                title:"母婴儿童",
                                list:[
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/international2.png",
                                        con:"奶粉"
                                    }
                                    
                                ]
                            },
                            {
                                title:"彩妆面护",
                                list:[
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    },
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    },
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    },
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    },
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    },
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    },
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    },
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    },
                                    {
                                        src:"./src/assets/images/international3.png",
                                        con:"防晒"
                                    }
                                ]
                            },
                            {
                                title:"身体护理",
                                list:[
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    },
                                    {
                                        src:"./src/assets/images/international4.png",
                                        con:"身体沐浴"
                                    }
                                   
                                    
                                ]
                            },
                            {
                                title:"营养保健",
                                list:[
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    }
                                ]
                            }
                        ]
                    }
                } else if( a.con == "奶粉尿裤"){
                    this.product = {
                        title:"母婴",
                        src:"",
                        products:[
                            {
                                title:"孕婴奶粉",
                                list:[
                                    {
                                        src:"./src/assets/images/n1.jpg",
                                        con:"一段奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/n1.jpg",
                                        con:"一段奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/n1.jpg",
                                        con:"一段奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/n1.jpg",
                                        con:"一段奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/n1.jpg",
                                        con:"一段奶粉"
                                    },
                                    {
                                        src:"./src/assets/images/n1.jpg",
                                        con:"一段奶粉"
                                    }
                                ]
                            },
                            {
                                title:"尿裤湿巾",
                                list:[
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    },
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    },
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    },
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    },
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    },
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    },
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    },
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    },
                                    {
                                        src:"./src/assets/images/n2.jpg",
                                        con:"NB号"
                                    }
                                    
                                ]
                            },
                            {
                                title:"营养辅食",
                                list:[
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    },
                                    {
                                        src:"./src/assets/images/n3.jpg",
                                        con:"米粉"
                                    }
                                    
                                ]
                            },
                            {
                                title:"洗护用品",
                                list:[
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    },
                                    {
                                        src:"./src/assets/images/n4.jpg",
                                        con:"驱蚊/防蚊"
                                    }
                                    
                                ]
                            },
                            {
                                title:"营养保健",
                                list:[
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    },
                                    {
                                        src:"./src/assets/images/international5.jpg",
                                        con:"膳食补充"
                                    }
                                ]
                            }
                        ]
                    }
                } else if(a.con == "珠宝首饰"){
                    this.product = {
                        title:"黄金珠宝",
                        src:"",
                        products:[
                            {
                                title:"优质黄金品牌",
                                list:[
                                    {
                                        src:"./src/assets/images/z1.jpg",
                                        con:"周大福"
                                    },
                                    {
                                        src:"./src/assets/images/z1.jpg",
                                        con:"周大福"
                                    },
                                    {
                                        src:"./src/assets/images/z1.jpg",
                                        con:"周大福"
                                    }
                                ]
                            },
                            {
                                title:"金银投资",
                                list:[
                                    {
                                        src:"./src/assets/images/z2.jpg",
                                        con:"投资金"
                                    },
                                    {
                                        src:"./src/assets/images/z2.jpg",
                                        con:"投资金"
                                    },
                                    {
                                        src:"./src/assets/images/z2.jpg",
                                        con:"投资金"
                                    }   
                                    
                                    
                                ]
                            },
                            {
                                title:"黄金饰品",
                                list:[
                                    {
                                        src:"./src/assets/images/z3.jpg",
                                        con:"黄金吊坠"
                                    },
                                    {
                                        src:"./src/assets/images/z3.jpg",
                                        con:"黄金吊坠"
                                    },
                                    {
                                        src:"./src/assets/images/z3.jpg",
                                        con:"黄金吊坠"
                                    },
                                    {
                                        src:"./src/assets/images/z3.jpg",
                                        con:"黄金吊坠"
                                    },
                                    {
                                        src:"./src/assets/images/z3.jpg",
                                        con:"黄金吊坠"
                                    },
                                    {
                                        src:"./src/assets/images/z3.jpg",
                                        con:"黄金吊坠"
                                    }
                                    
                                    
                                ]
                            },
                            {
                                title:"时尚饰品",
                                list:[
                                    {
                                        src:"./src/assets/images/z4.jpg",
                                        con:"项链"
                                    },
                                    {
                                        src:"./src/assets/images/z4.jpg",
                                        con:"项链"
                                    },
                                    {
                                        src:"./src/assets/images/z4.jpg",
                                        con:"项链"
                                    },
                                    {
                                        src:"./src/assets/images/z4.jpg",
                                        con:"项链"
                                    },
                                    {
                                        src:"./src/assets/images/z4.jpg",
                                        con:"项链"
                                    },
                                    {
                                        src:"./src/assets/images/z4.jpg",
                                        con:"项链"
                                    }
                                    
                                ]
                            },
                            {
                                title:"铂金饰品",
                                list:[
                                    {
                                        src:"./src/assets/images/z5.jpg",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/z5.jpg",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/z5.jpg",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/z5.jpg",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/z5.jpg",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/z5.jpg",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/z5.jpg",
                                        con:"铂金项链"
                                    }   
                                ]
                            }
                        ]
                    }
                } else if(a.con == "品质男装"){
                    this.product = {
                        title:"男装",
                        src:"",
                        products:[
                            {
                                title:"新品速递",
                                list:[
                                    {
                                        src:"./src/assets/images/man1.jpg",
                                        con:"衬衫"
                                    },
                                    {
                                        src:"./src/assets/images/man1.jpg",
                                        con:"衬衫"
                                    },
                                    {
                                        src:"./src/assets/images/man1.jpg",
                                        con:"衬衫"
                                    },
                                    {
                                        src:"./src/assets/images/man1.jpg",
                                        con:"衬衫"
                                    },
                                    {
                                        src:"./src/assets/images/man1.jpg",
                                        con:"衬衫"
                                    }
                                ]
                            },
                            {
                                title:"衬衫",
                                list:[
                                    {
                                        src:"./src/assets/images/man2.png",
                                        con:"定制衬衫"
                                    },
                                    {
                                        src:"./src/assets/images/man2.png",
                                        con:"定制衬衫"
                                    },
                                    {
                                        src:"./src/assets/images/man2.png",
                                        con:"定制衬衫"
                                    },
                                    {
                                        src:"./src/assets/images/man2.png",
                                        con:"定制衬衫"
                                    },
                                    {
                                        src:"./src/assets/images/man2.png",
                                        con:"定制衬衫"
                                    }
                                    
                                    
                                ]
                            },
                            {
                                title:"优质衬衫品牌",
                                list:[
                                    {
                                        src:"./src/assets/images/man3.jpg",
                                        con:"凡客"
                                    },
                                    {
                                        src:"./src/assets/images/man3.jpg",
                                        con:"凡客"
                                    },
                                    {
                                        src:"./src/assets/images/man3.jpg",
                                        con:"凡客"
                                    }
                                    
                                ]
                            },
                            {
                                title:"休闲裤",
                                list:[
                                    {
                                        src:"./src/assets/images/man4.jpg",
                                        con:"修身版型"
                                    },
                                    {
                                        src:"./src/assets/images/man4.jpg",
                                        con:"修身版型"
                                    },
                                    {
                                        src:"./src/assets/images/man4.jpg",
                                        con:"修身版型"
                                    },
                                    {
                                        src:"./src/assets/images/man4.jpg",
                                        con:"修身版型"
                                    },
                                    {
                                        src:"./src/assets/images/man4.jpg",
                                        con:"修身版型"
                                    }
                                    
                                ]
                            },
                            {
                                title:"优质休闲裤品牌",
                                list:[
                                    {
                                        src:"./src/assets/images/man5.png",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/man5.png",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/man5.png",
                                        con:"铂金项链"
                                    }
                                ]
                            },
                            {
                                title:"男士外套",
                                list:[
                                    {
                                        src:"./src/assets/images/man5.jpg",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/man5.jpg",
                                        con:"铂金项链"
                                    },
                                    {
                                        src:"./src/assets/images/man5.jpg",
                                        con:"铂金项链"
                                    }
                                ]
                            }
                        ]
                    }
                }
            }
        },
        components:{
            'v-recommend':recommend,
            'v-smart':smart,
            'v-family':family
        }
    }
</script>
<style scoped>
    header{
        width:100%;
        height:62px;
    }
    header .left{
        float:left;
        width:25%;
        height:62px;
        line-height:62px;
        text-align:center;
        font-size:18px;
    }
    header .right{
        width:60%;
        float:right;
        height:36px;
        background-color:#F7F7F7;
        border-radius:50px;
        margin-top:3%;
        margin-right:3%;
        line-height:36px;
        padding-left:10%;
        position:relative;
        color:rgb(153,153,153);
    }
    header .right span{
        position:absolute;
        left:11px;
        top:8px;
        width:20px;
        height:20px;
        background:url("../../assets/images/search.png") no-repeat;
        background-size:100%;
    }
    section nav{
        width:25%;
        float:left;
    }
    section main {
        width:70%;
        float:right;
    }
    section nav ul{
        width:100%;
    }
    section nav li{
        height:52px;
        line-height:52px;
        text-align:center;
        font-size:14px;
    }
    section>nav{
        height:calc(100vh - 62px);
        overflow: auto;
        
    }
    ul.type{
        padding-bottom: 40%;
    }
    ul.type li{
        background-color: #F9F9F9;
    }
    ul.type .current{
        background-color: #ffffff;
    }
</style>